# Generated by Django 5.1.4 on 2024-12-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
    ]
