# Generated by Django 5.1.4 on 2024-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_distance_ride_fare_alter_ride_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locationCity',
            field=models.CharField(default='San Jose', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='locationName',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
            preserve_default=False,
        ),
    ]
