# Generated by Django 5.1.4 on 2024-12-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='email',
        ),
    ]
