# Generated by Django 5.1.1 on 2024-11-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('distance', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
